source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZQLStarView_Example', :exclusive => true do
  pod 'ZQLStarView', :path => '../'
end

target 'ZQLStarView_Tests', :exclusive => true do
  pod 'ZQLStarView', :path => '../'

  
end
